server:
  port: 8084
spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345
    username: postgres
    url: jdbc:postgresql://localhost:5432/paymentdb
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    consumer:
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: paymentDelegation:com.example.paymentservice.dto.DelegationFromRidesRequest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: kafka:29092
      group-id: paymentGroup
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:29092
    bootstrap-servers: kafka:29092
topic:
  name:
    ride: payment-delegate
kafka:
  partitions:
    count: 5
  replicas:
    count: 1
feign:
  client:
    driver:
      name: DRIVER-SERVICE
      url: http://driver-service:8085
      path: /api/v1/drivers
    passenger:
      name: PASSENGER-SERVICE
      url: http://passenger-service:8082
      path: /api/v1/passengers
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
jwt:
  auth:
    converter:
      resource-id: cab-aggregator-client
      principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG